"use client"
import type { Metadata } from "next";

import { Btn, Title } from "@/app/components";

import clsx from "clsx";
import app from "@/styles/app.module.scss";

type GlobalErrorProps = {
  error: Error & { digest?: string },
  reset: () => void,
}

export const metadata: Metadata = {
  title: "EmCliques",
  description: "Generated by create next app",
  icons: {
    icon: [
      { 
        url: "/favicon--dark.ico",
        media: "(prefers-color-scheme: light)",
      },
      { 
        url: "/favicon--light.ico", 
        media: "(prefers-color-scheme: dark)",
      },
    ]
  }
};

export default function GlobalError(props: GlobalErrorProps) {
  const { error, reset }= props;

  return (
    <div className={ clsx(app.page, app.pageError) }>
      <div className={ app.titles }>
        <Title
          typeSeo={ 2 }
          typeStyle={ 3 }
          color="red"
          text="Erro Desconhecido"
          align="center"
          lightness="light"
        />
        
        <Title
          typeSeo={ 1 }
          typeStyle={ 2 }
          color="red"
          text="Ocorreu um erro ao processar sua requisição:"
          align="center"
        />
      </div>
      
      <div className={ app.block }>
        <div className={ app.meta }>
          <div className={ app.code }>
            <span>
              Código:
            </span>
            
            <strong>
              &nbsp;
              { error.digest }
            </strong>
          </div>

          <div className={ app.status }>
            <span>
              Status:
            </span>
            
            <strong>
              &nbsp;
              500
            </strong>
          </div>
        </div>

        <div className={ app.message }>
          Ocorreu um erro desconhecido ao processar sua requisição. 
          Por favor, entre em contato com nosso suporte ou tente novamente mais tarde.
        </div>
      </div>

      <div className={ app.btns }>
        <Btn
          type="button"
          onClick={ reset }
          bgColor="red"
          color="white"
          text="TENTAR NOVAMENTE"
          transition="growSmall"
        />

        <Btn
          type="link"
          href="/"
          color="red"
          borderColor="red"
          bgColor="white"
          text="VOLTAR PARA PÁGINA INICIAL"
          transition="bg"
          fillColor="red"
        />
      </div>
    </div>
  )
}