import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { Toaster } from "sonner";

import { QueryProvider } from "@/app/contexts/QueryProvider";
import { Navbar } from "@/app/components";

import clsx from "clsx";
import app from "@/styles/app.module.scss";
import "@/styles/app.scss";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-inter",
  display: "swap"
});

const poppins = Poppins({
  subsets: ["latin"], 
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "EmCliques",
  description: "Generated by create next app",
  icons: {
    icon: [
      { 
        url: "/favicon--dark.ico",
        media: "(prefers-color-scheme: light)",
      },
      { 
        url: "/favicon--light.ico", 
        media: "(prefers-color-scheme: dark)",
      },
    ]
  }
};

// TO-DO: review media queries and use @container query where applicable
export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      className={ clsx(inter.className, poppins.className) }
      lang="pt-BR"
    >
      <body className={ app.app }>
        <Toaster 
          position="top-center"
          expand={ true }
          richColors
          closeButton
        />

        <Navbar/>

        <QueryProvider>
          <div className={ app.main }>
            { children }
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
