version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: voteordie-backend
    env_file:
      - .env
    ports:
      - "8081:80"
    restart: unless-stopped
    # If you want to ensure backend waits for Supabase to be ready, consider using a wait-for-it script
    # depends_on:
    #   - supabase

# Note:
# - This compose file does NOT start Supabase itself.
# - Your backend will connect to Supabase using the credentials/host/port in your .env file (e.g., POSTGRES_SERVER, POSTGRES_USER, etc).
# - Make sure your .env points to the correct Supabase host/port (e.g., POSTGRES_SERVER=supabase-db or POSTGRES_SERVER=host.docker.internal for local dev).
